# Generated by Django 6.0.3 on 2026-03-29 09:50

import django.db.models.deletion
import roles.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('disciplines', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'IN Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('baseline_start_date', models.DateField(blank=True, null=True)),
                ('baseline_end_date', models.DateField(blank=True, null=True)),
                ('baseline_budget', models.FloatField(blank=True, null=True)),
                ('baseline_locked', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='branches.branch')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
            bases=(roles.mixins.AutoPermissionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('planned_weight', models.FloatField(help_text='Weight of this discipline as % of total project. All disciplines must sum to 100.')),
                ('budget_allocated', models.FloatField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_disciplines', to='disciplines.discipline')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_disciplines', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Discipline',
                'verbose_name_plural': 'Project Disciplines',
                'ordering': ['-updated', '-created'],
                'abstract': False,
                'unique_together': {('project', 'discipline')},
            },
        ),
    ]
