# Generated by Django 6.0.3 on 2026-03-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdiscipline',
            old_name='lead',
            new_name='manger',
        ),
    ]
