# Generated by Django 6.0.3 on 2026-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_lead_projectdiscipline_manger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdiscipline',
            old_name='manger',
            new_name='manager',
        ),
    ]
