# Generated by Django 6.0.3 on 2026-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_manger_projectdiscipline_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deputy_manager',
        ),
    ]
