# Generated by Django 6.0.3 on 2026-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='baseline_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='baseline_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='baseline_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
