# Generated by Django 6.0.3 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_baseline_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='baseline_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'IN Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdiscipline',
            name='budget_allocated',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectdiscipline',
            name='planned_weight',
            field=models.FloatField(help_text='Weight of this discipline as % of total project. All disciplines must sum to 100.'),
        ),
    ]
