# Generated by Django 6.0.3 on 2026-03-29 09:50

import django.db.models.deletion
import django.utils.timezone
import roles.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('planned_hours', models.FloatField(blank=True, null=True)),
                ('budgeted_cost', models.FloatField()),
                ('weight', models.FloatField(help_text='% weight of this task within its discipline. All tasks must sum to 100.')),
                ('measurement_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('units', 'Units (e.g. piles, columns)'), ('linear', 'Linear Measure (e.g. metres)'), ('hours', 'Hours'), ('lump_sum', 'Lump Sum (Done / Not Done)')], default='percentage', max_length=20)),
                ('target_value', models.FloatField(blank=True, help_text='Target quantity for units/linear/hours types. Leave blank for percentage and lump sum.', null=True)),
                ('unit_label', models.CharField(blank=True, help_text="Label for the unit of measure e.g. 'piles', 'metres', 'hours'.", max_length=50, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_tasks', to='employees.employee')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projectdiscipline')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
            bases=(roles.mixins.AutoPermissionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value_achieved', models.FloatField(help_text='For units/linear/hours: quantity achieved THIS session (additive). For percentage: new cumulative % complete (latest wins). For lump_sum: 1 = done, 0 = not done.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_updates', to='employees.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Update',
                'verbose_name_plural': 'Task Updates',
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
    ]
