# Generated by Django 6.0.3 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budgeted_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Target quantity for units/linear/hours types. Leave blank for percentage and lump sum.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.FloatField(help_text='% weight of this task within its discipline. All tasks must sum to 100.'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='actual_cost',
            field=models.FloatField(help_text='Actual cost incurred during this update session.'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='value_achieved',
            field=models.FloatField(help_text='For units/linear/hours: quantity achieved THIS session (additive). For percentage: new cumulative % complete (latest wins). For lump_sum: 1 = done, 0 = not done.'),
        ),
    ]
