# Generated by Django 6.0.3 on 2026-03-16 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_budgeted_cost_alter_task_planned_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
