# Generated by Django 6.0.3 on 2026-03-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskupdate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskupdate',
            name='actual_cost',
        ),
    ]
