# Generated by Django 6.0.3 on 2026-03-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discipline_mix', models.CharField(help_text="Sorted comma-separated discipline codes e.g. 'arch,eng,qs'", max_length=255)),
                ('actual_duration', models.PositiveIntegerField(help_text='Actual project duration in days.')),
                ('final_spi', models.DecimalField(decimal_places=3, max_digits=5)),
                ('final_cpi', models.DecimalField(decimal_places=3, max_digits=5)),
                ('team_size', models.PositiveIntegerField()),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_at_completion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Snapshot',
                'verbose_name_plural': 'Project Snapshots',
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
    ]
