# Generated by Django 6.0.3 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsnapshot',
            name='budget_at_completion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectsnapshot',
            name='final_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectsnapshot',
            name='final_cpi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectsnapshot',
            name='final_spi',
            field=models.FloatField(),
        ),
    ]
